version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yze200078
    ports:
      - "3305:3306"
    volumes:
      - ./.mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - mynetwork

  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork: